spring.application.name=repill
server.port=8080

openai.api-key=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
openai.model=gpt-4.1-mini

ocr.invoke-url=https://s6dhznav0l.apigw.ntruss.com/custom/v1/53330/71dc489ca2eca467858d562332bcc95d2bc1995fa7cecae3909081492e291d3f/general
ocr.secret-key=R2lHdVRZWXRudGJTY3preVFjbVBEQ1ZBQmNseGdMSlA=

drug.api.service-key=0fcfa9396ffe9d63bdf6a658409251300d9985f9b2a06e1f8d3524ab6bed440f

file.upload-dir=C:/uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.mjcczeqcqlnsaapabdlc
spring.datasource.password=Re:pill1234!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
